version: '3.5'
services:
  chat-px-app:
    container_name: chat-px-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:3000
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_API=http://localhost:4000/graphql
      - REACT_APP_SOCKET_API=ws://localhost:4000/graphql
    restart: unless-stopped
